#!/usr/bin/env bash
set -euo pipefail

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
run_id=${MASI_P4_RUN_ID:-"$(date -u +%Y%m%dT%H%M%SZ)-$$"}
started_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
qualification_mode=${MASI_P4_QUALIFICATION_MODE:-formal}
if [ "$qualification_mode" != formal ] && [ "$qualification_mode" != rehearsal ]; then
  echo "MASI_P4_QUALIFICATION_MODE must be formal or rehearsal" >&2
  exit 64
fi
evidence_dir="$repo_root/evidence/p4-switch/$run_id"
certificate_dir="$repo_root/out/p4-switch-e2e/$run_id/certs"
compiled_artifact_dir="$repo_root/out/p4-switch-e2e/$run_id/compiled-artifacts"
mininet_artifact_dir="$repo_root/out/p4-switch-e2e/$run_id/mininet-artifacts"
project_name="masip4e2e${run_id//[^a-zA-Z0-9]/}"
project_name=${project_name,,}
project_name=${project_name:0:56}

mkdir -p "$evidence_dir" "$certificate_dir" "$compiled_artifact_dir"
chown 65532:65532 "$evidence_dir"
chmod 0770 "$evidence_dir"
"$repo_root/testkit/p4_switch/scripts/prepare-certs.sh" "$certificate_dir"

readarray -t expected_images < <(
  python3 - "$repo_root" <<'PY'
import json, sys
from pathlib import Path
root=Path(sys.argv[1])
p4=json.load(open(root / "contracts/profiles/v1/p4-stateless-firewall-bmv2.json", encoding="utf-8"))
runner=json.load(open(root / "contracts/profiles/v1/e2e-runner-compose.json", encoding="utf-8"))
print(p4["target"]["runtime_image"])
print(runner["runner_image_digest"])
PY
)
runtime_ref=${MASI_P4_RUNTIME_IMAGE:-${expected_images[0]}}
runner_ref=${MASI_P4_RUNNER_IMAGE:-masi-nids/p4-switch-e2e-runner:local}
expected_runtime_digest=${expected_images[0]#*@}
expected_runner_digest=${expected_images[1]}
runtime_image=$(docker image inspect "$runtime_ref" --format '{{.Id}}')
runner_image=$(docker image inspect "$runner_ref" --format '{{.Id}}')
if [ "$runtime_image" != "$expected_runtime_digest" ]; then
  echo "runtime image mismatch: expected $expected_runtime_digest, got $runtime_image" >&2
  exit 65
fi
if [ "$runner_image" != "$expected_runner_digest" ]; then
  echo "runner image mismatch: expected $expected_runner_digest, got $runner_image" >&2
  exit 65
fi

export MASI_P4_RUNTIME_IMAGE="$runtime_ref"
export MASI_P4_CERT_DIR="$certificate_dir"
export MASI_P4_EVIDENCE_DIR="$evidence_dir"
compose=(docker compose -p "$project_name" -f "$repo_root/deploy/p4-switch/compose.module-e2e.yaml")

cleanup() {
  docker rm -f "${project_name}-performance" "${project_name}-soak" >/dev/null 2>&1 || true
  "${compose[@]}" down --volumes --remove-orphans >/dev/null 2>&1 || true
}
trap cleanup EXIT

wait_for_one_shot() {
  local service_name=$1
  local service_id
  local service_running
  local service_exit
  service_id=$("${compose[@]}" ps -aq "$service_name")
  if [ -z "$service_id" ]; then
    printf 'service %s has no container\n' "$service_name" >&2
    return 1
  fi
  for _ in $(seq 1 120); do
    service_running=$(docker inspect "$service_id" --format '{{.State.Running}}')
    if [ "$service_running" = false ]; then
      service_exit=$(docker inspect "$service_id" --format '{{.State.ExitCode}}')
      if [ "$service_exit" -ne 0 ]; then
        printf 'service %s exited with status %s\n' "$service_name" "$service_exit" >&2
        return "$service_exit"
      fi
      return 0
    fi
    sleep 0.5
  done
  printf 'timed out waiting for service %s\n' "$service_name" >&2
  return 124
}

wait_for_switch_health() {
  local switch_id
  local switch_health
  local switch_running
  switch_id=$("${compose[@]}" ps -q switch)
  if [ -z "$switch_id" ]; then
    printf 'switch has no running container\n' >&2
    return 1
  fi
  for _ in $(seq 1 120); do
    switch_running=$(docker inspect "$switch_id" --format '{{.State.Running}}')
    switch_health=$(docker inspect "$switch_id" --format '{{.State.Health.Status}}')
    if [ "$switch_running" = false ]; then
      printf 'switch exited before becoming healthy\n' >&2
      return 1
    fi
    if [ "$switch_health" = healthy ]; then
      return 0
    fi
    sleep 0.5
  done
  printf 'timed out waiting for the switch health check\n' >&2
  return 124
}

firewall_fingerprint() {
  {
    if command -v nft >/dev/null 2>&1; then nft --stateless list ruleset 2>/dev/null || true; fi
    if command -v iptables-save >/dev/null 2>&1; then
      iptables-save 2>/dev/null | sed '/^# Generated by /d; /^# Completed on /d' || true
    fi
    if command -v ufw >/dev/null 2>&1; then ufw status 2>/dev/null || true; fi
  } | sha256sum | cut -d' ' -f1
}

firewall_before=$(firewall_fingerprint)

set +e
docker run --rm --network none --read-only --user 65532:65532 \
  --cap-drop ALL --security-opt no-new-privileges:true \
  --env PYTHONDONTWRITEBYTECODE=1 \
  --volume "$repo_root:/workspace:ro" --volume "$evidence_dir:/evidence" \
  "$runner_ref" python testkit/p4_switch/scripts/probe-runner-environment.py \
  --repo /workspace --runner-digest "$runner_image" \
  --output /evidence/runner-environment.json \
  >"$evidence_dir/runner-environment.log" 2>&1
runner_environment_status=$?
set -e

set +e
python3 -m unittest discover \
  -s "$repo_root/testkit/p4_switch/tests" -p 'test_*.py' -v \
  >"$evidence_dir/unit.log" 2>&1
unit_status=$?
set -e
unit_result=PASS
if [ "$unit_status" -ne 0 ]; then unit_result=FAIL; fi
python3 "$repo_root/testkit/p4_switch/scripts/record-command.py" \
  unit TEST-P4-STATIC-CONTRACT-001 "$unit_result" "$unit_status" \
  "$evidence_dir/unit.log" "$evidence_dir/unit.json"

set +e
"$repo_root/testkit/p4_switch/scripts/run-p4testgen.sh" "$evidence_dir"
p4testgen_status=$?
set -e
if [ "$p4testgen_status" -ne 0 ]; then
  python3 "$repo_root/testkit/p4_switch/scripts/record-command.py" \
    p4testgen TEST-P4TESTGEN-001 FAIL "$p4testgen_status" \
    "$evidence_dir/p4testgen.log" "$evidence_dir/p4testgen.json"
fi

set +e
"$repo_root/p4/scripts/compile.sh" "$mininet_artifact_dir" \
  >"$evidence_dir/mininet-compile.log" 2>&1
mininet_compile_status=$?
set -e
mininet_status=$mininet_compile_status
if [ "$mininet_compile_status" -eq 0 ]; then
  set +e
  python3 "$repo_root/testkit/p4_switch/mininet/run_mininet_e2e.py" \
    "$repo_root" "$mininet_artifact_dir" "$certificate_dir" \
    "$runner_image" "$run_id" "$evidence_dir/mininet.json" \
    "$evidence_dir/mininet-bmv2.log" >"$evidence_dir/mininet.log" 2>&1
  mininet_status=$?
  set -e
fi

compiler_started_ms=$(date +%s%3N)
"${compose[@]}" up -d compiler switch net-init
compiler_id=$("${compose[@]}" ps -q compiler)
for _ in $(seq 1 120); do
  compiler_running=$(docker inspect "$compiler_id" --format '{{.State.Running}}')
  if [ "$compiler_running" = false ]; then break; fi
  sleep 0.5
done
compiler_finished_ms=$(date +%s%3N)
compiler_duration_ms=$((compiler_finished_ms - compiler_started_ms))
compiler_status=$(docker inspect "$compiler_id" --format '{{.State.ExitCode}}')
"${compose[@]}" logs --no-color compiler >"$evidence_dir/compiler.log" 2>&1
compiler_result=PASS
if [ "$compiler_status" -ne 0 ]; then compiler_result=FAIL; fi
python3 "$repo_root/testkit/p4_switch/scripts/record-command.py" \
  compiler TEST-P4-COMPILE-001 "$compiler_result" "$compiler_status" \
  "$evidence_dir/compiler.log" "$evidence_dir/compiler.json" "$compiler_duration_ms"
docker cp "$compiler_id:/artifacts/." "$compiled_artifact_dir/"
wait_for_one_shot net-init
wait_for_switch_health

ptf_parameters="artifacts='/artifacts';cert_dir='/certs';evidence_dir='/evidence';address='127.0.0.1:9559'"
set +e
"${compose[@]}" run --rm --no-deps runner ptf \
  --log-dir /tmp/ptf --test-dir testkit/p4_switch/ptf \
  --interface 1@masi-p1 --interface 2@masi-p2 \
  --test-case-timeout 900 --test-params "$ptf_parameters" \
  masi_switch_test.MasiSwitchE2E >"$evidence_dir/ptf-functional.log" 2>&1
functional_status=$?
set -e

performance_name="${project_name}-performance"
performance_arguments=(
  python testkit/p4_switch/scripts/run-performance.py
  --repo /workspace --artifacts /artifacts --cert-dir /certs
  --output /evidence/performance-workload.json --run-id "$run_id"
  --runtime-digest "$runtime_image" --runner-digest "$runner_image"
  --mode "$qualification_mode"
)
if [ "$qualification_mode" = rehearsal ]; then
  performance_arguments+=(
    --rehearsal-warmup-seconds "${MASI_P4_REHEARSAL_WARMUP_SECONDS:-1}"
    --rehearsal-measurement-seconds "${MASI_P4_REHEARSAL_MEASUREMENT_SECONDS:-1}"
    --rehearsal-repeats "${MASI_P4_REHEARSAL_REPEATS:-1}"
  )
fi
docker rm -f "$performance_name" >/dev/null 2>&1 || true
"${compose[@]}" run --name "$performance_name" -d --no-deps runner \
  "${performance_arguments[@]}" >/dev/null
performance_id=$(docker inspect "$performance_name" --format '{{.Id}}')
switch_id=$("${compose[@]}" ps -q switch)
python3 "$repo_root/testkit/p4_switch/scripts/sample-container-resources.py" \
  --switch-id "$switch_id" --runner-id "$performance_id" \
  --output "$evidence_dir/performance-resources.jsonl" \
  --interval-seconds 1 --max-samples 1200 &
performance_sampler_pid=$!
performance_status=$(docker wait "$performance_id")
docker logs "$performance_id" >"$evidence_dir/performance-workload.log" 2>&1
wait "$performance_sampler_pid"
docker rm "$performance_id" >/dev/null
set +e
python3 "$repo_root/testkit/p4_switch/scripts/finalize-performance.py" \
  --repo "$repo_root" --workload "$evidence_dir/performance-workload.json" \
  --resources "$evidence_dir/performance-resources.jsonl" \
  --compiler "$evidence_dir/compiler.json" --output "$evidence_dir/performance.json"
performance_finalize_status=$?
set -e

old_switch_id=$("${compose[@]}" ps -q switch)
old_switch_started=$(docker inspect "$old_switch_id" --format '{{.State.StartedAt}}')
"${compose[@]}" logs --no-color switch >"$evidence_dir/bmv2-before-crash.log" 2>&1
"${compose[@]}" kill --signal SIGKILL switch >/dev/null
for _ in $(seq 1 60); do
  switch_running=$(docker inspect "$old_switch_id" --format '{{.State.Running}}')
  if [ "$switch_running" = false ]; then break; fi
  sleep 0.25
done
old_switch_exit=$(docker inspect "$old_switch_id" --format '{{.State.ExitCode}}')
"${compose[@]}" up -d --force-recreate switch net-init
new_switch_id=$("${compose[@]}" ps -q switch)
new_switch_started=$(docker inspect "$new_switch_id" --format '{{.State.StartedAt}}')
wait_for_one_shot net-init
wait_for_switch_health
set +e
python3 "$repo_root/testkit/p4_switch/scripts/record-crash.py" \
  "$old_switch_id" "$old_switch_started" "$old_switch_exit" \
  "$new_switch_id" "$new_switch_started" "$evidence_dir/crash-orchestration.json"
crash_orchestration_status=$?
"${compose[@]}" run --rm --no-deps runner ptf \
  --log-dir /tmp/ptf --test-dir testkit/p4_switch/ptf \
  --interface 1@masi-p1 --interface 2@masi-p2 \
  --test-case-timeout 180 --test-params "$ptf_parameters" \
  masi_switch_test.MasiSwitchCrashRecovery \
  >"$evidence_dir/ptf-crash-recovery.log" 2>&1
recovery_status=$?
set -e
"${compose[@]}" logs --no-color switch >"$evidence_dir/bmv2-after-restart.log" 2>&1

lifecycle_dir="$evidence_dir/lifecycle-cycles"
install -d -o 65532 -g 65532 -m 0770 "$lifecycle_dir"
lifecycle_cycle_status=0
for cycle in $(seq 1 20); do
  signal_name=SIGINT
  if [ $((cycle % 2)) -eq 0 ]; then signal_name=SIGTERM; fi
  pre_probe="$lifecycle_dir/pre-$(printf '%02d' "$cycle").json"
  post_probe="$lifecycle_dir/post-$(printf '%02d' "$cycle").json"
  shutdown_log="$lifecycle_dir/shutdown-$(printf '%02d' "$cycle").log"
  cycle_json="$lifecycle_dir/cycle-$(printf '%02d' "$cycle").json"
  set +e
  "${compose[@]}" run --rm --no-deps runner python \
    testkit/p4_switch/scripts/probe-public-boundary.py \
    --artifacts /artifacts --cert-dir /certs --output "/evidence/lifecycle-cycles/${pre_probe##*/}" \
    --run-identity "$run_id:lifecycle:$cycle:pre" --election-id $((300 + cycle * 2)) \
    >"$lifecycle_dir/pre-$(printf '%02d' "$cycle").log" 2>&1
  pre_status=$?
  set -e
  lifecycle_old_id=$("${compose[@]}" ps -q switch)
  lifecycle_stop_started_ms=$(date +%s%3N)
  docker kill --signal "$signal_name" "$lifecycle_old_id" >/dev/null
  forced_kill=false
  for _ in $(seq 1 100); do
    switch_running=$(docker inspect "$lifecycle_old_id" --format '{{.State.Running}}')
    if [ "$switch_running" = false ]; then break; fi
    sleep 0.1
  done
  switch_running=$(docker inspect "$lifecycle_old_id" --format '{{.State.Running}}')
  if [ "$switch_running" = true ]; then
    forced_kill=true
    docker kill --signal SIGKILL "$lifecycle_old_id" >/dev/null
  fi
  lifecycle_stop_finished_ms=$(date +%s%3N)
  lifecycle_stop_duration_ms=$((lifecycle_stop_finished_ms - lifecycle_stop_started_ms))
  lifecycle_old_exit=$(docker inspect "$lifecycle_old_id" --format '{{.State.ExitCode}}')
  lifecycle_oom=$(docker inspect "$lifecycle_old_id" --format '{{.State.OOMKilled}}')
  docker logs "$lifecycle_old_id" >"$shutdown_log" 2>&1
  "${compose[@]}" up -d --force-recreate switch net-init
  lifecycle_new_id=$("${compose[@]}" ps -q switch)
  wait_for_one_shot net-init
  wait_for_switch_health
  old_removed=false
  if ! docker inspect "$lifecycle_old_id" >/dev/null 2>&1; then old_removed=true; fi
  set +e
  "${compose[@]}" run --rm --no-deps runner python \
    testkit/p4_switch/scripts/probe-public-boundary.py \
    --artifacts /artifacts --cert-dir /certs --output "/evidence/lifecycle-cycles/${post_probe##*/}" \
    --run-identity "$run_id:lifecycle:$cycle:post" --election-id $((301 + cycle * 2)) \
    >"$lifecycle_dir/post-$(printf '%02d' "$cycle").log" 2>&1
  post_status=$?
  python3 "$repo_root/testkit/p4_switch/scripts/record-lifecycle-cycle.py" \
    --cycle "$cycle" --signal "$signal_name" --old-id "$lifecycle_old_id" \
    --old-exit "$lifecycle_old_exit" --stop-duration-ms "$lifecycle_stop_duration_ms" \
    --forced-kill "$forced_kill" --oom-killed "$lifecycle_oom" \
    --new-id "$lifecycle_new_id" --old-removed "$old_removed" \
    --pre-probe "$pre_probe" --post-probe "$post_probe" \
    --shutdown-log "$shutdown_log" --output "$cycle_json"
  record_status=$?
  set -e
  if [ "$pre_status" -ne 0 ] || [ "$post_status" -ne 0 ] || [ "$record_status" -ne 0 ]; then
    lifecycle_cycle_status=1
  fi
done
set +e
python3 "$repo_root/testkit/p4_switch/scripts/finalize-lifecycle.py" \
  --cycles-dir "$lifecycle_dir" --runtime-digest "$runtime_image" \
  --output "$evidence_dir/lifecycle.json"
lifecycle_finalize_status=$?
set -e

soak_name="${project_name}-soak"
soak_arguments=(
  python testkit/p4_switch/scripts/run-soak.py
  --repo /workspace --artifacts /artifacts --cert-dir /certs
  --output /evidence/soak-workload.json --run-id "$run_id"
  --runtime-digest "$runtime_image" --runner-digest "$runner_image"
  --mode "$qualification_mode"
)
if [ "$qualification_mode" = rehearsal ]; then
  soak_arguments+=(
    --rehearsal-warmup-seconds "${MASI_P4_REHEARSAL_WARMUP_SECONDS:-1}"
    --rehearsal-phase-seconds "${MASI_P4_REHEARSAL_PHASE_SECONDS:-2}"
    --rehearsal-sample-seconds "${MASI_P4_REHEARSAL_SAMPLE_SECONDS:-1}"
  )
fi
docker rm -f "$soak_name" >/dev/null 2>&1 || true
"${compose[@]}" run --name "$soak_name" -d --no-deps runner \
  "${soak_arguments[@]}" >/dev/null
soak_id=$(docker inspect "$soak_name" --format '{{.Id}}')
switch_id=$("${compose[@]}" ps -q switch)
python3 "$repo_root/testkit/p4_switch/scripts/sample-container-resources.py" \
  --switch-id "$switch_id" --runner-id "$soak_id" \
  --output "$evidence_dir/soak-resources.jsonl" \
  --interval-seconds "$([ "$qualification_mode" = formal ] && echo 10 || echo 1)" \
  --max-samples "$([ "$qualification_mode" = formal ] && echo 400 || echo 120)" &
soak_sampler_pid=$!
soak_status=$(docker wait "$soak_id")
docker logs "$soak_id" >"$evidence_dir/soak-workload.log" 2>&1
wait "$soak_sampler_pid"
docker rm "$soak_id" >/dev/null
set +e
python3 "$repo_root/testkit/p4_switch/scripts/finalize-soak.py" \
  --repo "$repo_root" --workload "$evidence_dir/soak-workload.json" \
  --resources "$evidence_dir/soak-resources.jsonl" \
  --evidence-output "$evidence_dir/soak-evidence.json" \
  --phase-output "$evidence_dir/soak.json" --runner-container-removed true
soak_finalize_status=$?
set -e

supply_status=2
if [ "$qualification_mode" = formal ]; then
  source_archive=${MASI_BMV2_SOURCE_ARCHIVE:-/tmp/behavioral-model-693e69e634fedf007964a069fdd69acc441a5f80.tar.gz}
  trivy_cache=${MASI_TRIVY_CACHE:-$repo_root/out/supply-chain/trivy-cache}
  cosign_key_dir=${MASI_COSIGN_KEY_DIR:-$repo_root/.masi-secrets/cosign}
  set +e
  "$repo_root/testkit/p4_switch/scripts/run-supply-chain.sh" \
    "$evidence_dir" "$compiled_artifact_dir" "$run_id" \
    "$runtime_ref" "$runner_ref" "$source_archive" "$trivy_cache" "$cosign_key_dir" \
    >"$evidence_dir/supply-chain.log" 2>&1
  supply_status=$?
  set -e
else
  python3 "$repo_root/testkit/p4_switch/scripts/record-gate.py" \
    --phase supply-chain --level REHEARSAL --result HOLD \
    --reason SHORT_REHEARSAL_DOES_NOT_REUSE_FORMAL_SUPPLY_EVIDENCE \
    --output "$evidence_dir/supply-chain.json"
fi

firewall_after=$(firewall_fingerprint)
set +e
"${compose[@]}" run --rm --no-deps runner python \
  testkit/p4_switch/scripts/aggregate-evidence.py \
  /workspace /evidence /artifacts "$run_id" "$started_at" \
  "$runner_image" "$runtime_image" "$firewall_before" "$firewall_after" \
  /evidence/qualification-evidence.json
aggregate_status=$?
set -e

printf '%s\n' \
  "run_id=$run_id" \
  "mode=$qualification_mode" \
  "runtime_image=$runtime_image" \
  "runner_image=$runner_image" \
  "runner_environment_status=$runner_environment_status" \
  "unit_status=$unit_status" \
  "p4testgen_status=$p4testgen_status" \
  "mininet_compile_status=$mininet_compile_status" \
  "mininet_status=$mininet_status" \
  "compiler_status=$compiler_status" \
  "functional_status=$functional_status" \
  "performance_status=$performance_status" \
  "performance_finalize_status=$performance_finalize_status" \
  "crash_orchestration_status=$crash_orchestration_status" \
  "recovery_status=$recovery_status" \
  "lifecycle_cycle_status=$lifecycle_cycle_status" \
  "lifecycle_finalize_status=$lifecycle_finalize_status" \
  "soak_status=$soak_status" \
  "soak_finalize_status=$soak_finalize_status" \
  "supply_status=$supply_status" \
  "aggregate_status=$aggregate_status" \
  "evidence=$evidence_dir/qualification-evidence.json"

if [ "$runner_environment_status" -ne 0 ] \
  || [ "$unit_status" -ne 0 ] \
  || [ "$p4testgen_status" -ne 0 ] \
  || [ "$mininet_compile_status" -ne 0 ] \
  || [ "$mininet_status" -ne 0 ] \
  || [ "$compiler_status" -ne 0 ] \
  || [ "$functional_status" -ne 0 ] \
  || [ "$performance_status" -ne 0 ] \
  || { [ "$performance_finalize_status" -ne 0 ] && [ "$performance_finalize_status" -ne 2 ]; } \
  || [ "$crash_orchestration_status" -ne 0 ] \
  || [ "$recovery_status" -ne 0 ] \
  || [ "$lifecycle_cycle_status" -ne 0 ] \
  || [ "$lifecycle_finalize_status" -ne 0 ] \
  || [ "$soak_status" -ne 0 ] \
  || { [ "$soak_finalize_status" -ne 0 ] && [ "$soak_finalize_status" -ne 2 ]; } \
  || { [ "$supply_status" -ne 0 ] && [ "$supply_status" -ne 2 ]; } \
  || { [ "$aggregate_status" -ne 0 ] && [ "$aggregate_status" -ne 2 ]; }; then
  exit 1
fi
if [ "$aggregate_status" -eq 2 ]; then exit 2; fi
