# TYPE      DATABASE                    USER                    ADDRESS          METHOD
local       all                         all                                      scram-sha-256
hostssl     replication                 masi_replication_login  0.0.0.0/0        scram-sha-256 clientcert=verify-full
hostssl     replication                 masi_replication_login  ::/0             scram-sha-256 clientcert=verify-full
hostssl     masi_state_module_test      all                     0.0.0.0/0        scram-sha-256 clientcert=verify-full
hostssl     masi_state_module_test      all                     ::/0             scram-sha-256 clientcert=verify-full
hostssl     all                         masi_migration_login    0.0.0.0/0        scram-sha-256 clientcert=verify-full
hostssl     all                         masi_migration_login    ::/0             scram-sha-256 clientcert=verify-full
hostnossl   all                         all                     0.0.0.0/0        reject
hostnossl   all                         all                     ::/0             reject
