// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: control-adapter/v1/control_adapter.proto

package adapterv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeploymentAdapter_StagePool_FullMethodName         = "/masi.control.adapter.v1.DeploymentAdapter/StagePool"
	DeploymentAdapter_StartReplicas_FullMethodName     = "/masi.control.adapter.v1.DeploymentAdapter/StartReplicas"
	DeploymentAdapter_WarmupAndCapacity_FullMethodName = "/masi.control.adapter.v1.DeploymentAdapter/WarmupAndCapacity"
)

// DeploymentAdapterClient is the client API for DeploymentAdapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeploymentAdapterClient interface {
	StagePool(ctx context.Context, in *PoolGenerationRequest, opts ...grpc.CallOption) (*DeploymentActionReply, error)
	StartReplicas(ctx context.Context, in *PoolGenerationRequest, opts ...grpc.CallOption) (*PoolReadback, error)
	WarmupAndCapacity(ctx context.Context, in *PoolGenerationRequest, opts ...grpc.CallOption) (*CapacityReadback, error)
}

type deploymentAdapterClient struct {
	cc grpc.ClientConnInterface
}

func NewDeploymentAdapterClient(cc grpc.ClientConnInterface) DeploymentAdapterClient {
	return &deploymentAdapterClient{cc}
}

func (c *deploymentAdapterClient) StagePool(ctx context.Context, in *PoolGenerationRequest, opts ...grpc.CallOption) (*DeploymentActionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeploymentActionReply)
	err := c.cc.Invoke(ctx, DeploymentAdapter_StagePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentAdapterClient) StartReplicas(ctx context.Context, in *PoolGenerationRequest, opts ...grpc.CallOption) (*PoolReadback, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoolReadback)
	err := c.cc.Invoke(ctx, DeploymentAdapter_StartReplicas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentAdapterClient) WarmupAndCapacity(ctx context.Context, in *PoolGenerationRequest, opts ...grpc.CallOption) (*CapacityReadback, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapacityReadback)
	err := c.cc.Invoke(ctx, DeploymentAdapter_WarmupAndCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeploymentAdapterServer is the server API for DeploymentAdapter service.
// All implementations must embed UnimplementedDeploymentAdapterServer
// for forward compatibility.
type DeploymentAdapterServer interface {
	StagePool(context.Context, *PoolGenerationRequest) (*DeploymentActionReply, error)
	StartReplicas(context.Context, *PoolGenerationRequest) (*PoolReadback, error)
	WarmupAndCapacity(context.Context, *PoolGenerationRequest) (*CapacityReadback, error)
	mustEmbedUnimplementedDeploymentAdapterServer()
}

// UnimplementedDeploymentAdapterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeploymentAdapterServer struct{}

func (UnimplementedDeploymentAdapterServer) StagePool(context.Context, *PoolGenerationRequest) (*DeploymentActionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method StagePool not implemented")
}
func (UnimplementedDeploymentAdapterServer) StartReplicas(context.Context, *PoolGenerationRequest) (*PoolReadback, error) {
	return nil, status.Error(codes.Unimplemented, "method StartReplicas not implemented")
}
func (UnimplementedDeploymentAdapterServer) WarmupAndCapacity(context.Context, *PoolGenerationRequest) (*CapacityReadback, error) {
	return nil, status.Error(codes.Unimplemented, "method WarmupAndCapacity not implemented")
}
func (UnimplementedDeploymentAdapterServer) mustEmbedUnimplementedDeploymentAdapterServer() {}
func (UnimplementedDeploymentAdapterServer) testEmbeddedByValue()                           {}

// UnsafeDeploymentAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeploymentAdapterServer will
// result in compilation errors.
type UnsafeDeploymentAdapterServer interface {
	mustEmbedUnimplementedDeploymentAdapterServer()
}

func RegisterDeploymentAdapterServer(s grpc.ServiceRegistrar, srv DeploymentAdapterServer) {
	// If the following call panics, it indicates UnimplementedDeploymentAdapterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeploymentAdapter_ServiceDesc, srv)
}

func _DeploymentAdapter_StagePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentAdapterServer).StagePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentAdapter_StagePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentAdapterServer).StagePool(ctx, req.(*PoolGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeploymentAdapter_StartReplicas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentAdapterServer).StartReplicas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentAdapter_StartReplicas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentAdapterServer).StartReplicas(ctx, req.(*PoolGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeploymentAdapter_WarmupAndCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentAdapterServer).WarmupAndCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentAdapter_WarmupAndCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentAdapterServer).WarmupAndCapacity(ctx, req.(*PoolGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeploymentAdapter_ServiceDesc is the grpc.ServiceDesc for DeploymentAdapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeploymentAdapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "masi.control.adapter.v1.DeploymentAdapter",
	HandlerType: (*DeploymentAdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StagePool",
			Handler:    _DeploymentAdapter_StagePool_Handler,
		},
		{
			MethodName: "StartReplicas",
			Handler:    _DeploymentAdapter_StartReplicas_Handler,
		},
		{
			MethodName: "WarmupAndCapacity",
			Handler:    _DeploymentAdapter_WarmupAndCapacity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control-adapter/v1/control_adapter.proto",
}

const (
	PluginStatisticsExecutor_ExecuteStatistics_FullMethodName = "/masi.control.adapter.v1.PluginStatisticsExecutor/ExecuteStatistics"
)

// PluginStatisticsExecutorClient is the client API for PluginStatisticsExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginStatisticsExecutorClient interface {
	ExecuteStatistics(ctx context.Context, in *StatisticsExecutionRequest, opts ...grpc.CallOption) (*StatisticsExecutionReply, error)
}

type pluginStatisticsExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginStatisticsExecutorClient(cc grpc.ClientConnInterface) PluginStatisticsExecutorClient {
	return &pluginStatisticsExecutorClient{cc}
}

func (c *pluginStatisticsExecutorClient) ExecuteStatistics(ctx context.Context, in *StatisticsExecutionRequest, opts ...grpc.CallOption) (*StatisticsExecutionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatisticsExecutionReply)
	err := c.cc.Invoke(ctx, PluginStatisticsExecutor_ExecuteStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginStatisticsExecutorServer is the server API for PluginStatisticsExecutor service.
// All implementations must embed UnimplementedPluginStatisticsExecutorServer
// for forward compatibility.
type PluginStatisticsExecutorServer interface {
	ExecuteStatistics(context.Context, *StatisticsExecutionRequest) (*StatisticsExecutionReply, error)
	mustEmbedUnimplementedPluginStatisticsExecutorServer()
}

// UnimplementedPluginStatisticsExecutorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginStatisticsExecutorServer struct{}

func (UnimplementedPluginStatisticsExecutorServer) ExecuteStatistics(context.Context, *StatisticsExecutionRequest) (*StatisticsExecutionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteStatistics not implemented")
}
func (UnimplementedPluginStatisticsExecutorServer) mustEmbedUnimplementedPluginStatisticsExecutorServer() {
}
func (UnimplementedPluginStatisticsExecutorServer) testEmbeddedByValue() {}

// UnsafePluginStatisticsExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginStatisticsExecutorServer will
// result in compilation errors.
type UnsafePluginStatisticsExecutorServer interface {
	mustEmbedUnimplementedPluginStatisticsExecutorServer()
}

func RegisterPluginStatisticsExecutorServer(s grpc.ServiceRegistrar, srv PluginStatisticsExecutorServer) {
	// If the following call panics, it indicates UnimplementedPluginStatisticsExecutorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginStatisticsExecutor_ServiceDesc, srv)
}

func _PluginStatisticsExecutor_ExecuteStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticsExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginStatisticsExecutorServer).ExecuteStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginStatisticsExecutor_ExecuteStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginStatisticsExecutorServer).ExecuteStatistics(ctx, req.(*StatisticsExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginStatisticsExecutor_ServiceDesc is the grpc.ServiceDesc for PluginStatisticsExecutor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginStatisticsExecutor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "masi.control.adapter.v1.PluginStatisticsExecutor",
	HandlerType: (*PluginStatisticsExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteStatistics",
			Handler:    _PluginStatisticsExecutor_ExecuteStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control-adapter/v1/control_adapter.proto",
}
