// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.12.4
// source: control-adapter/v1/control_adapter.proto

package adapterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PoolGenerationRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion             string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	LogicalPoolId             string                 `protobuf:"bytes,2,opt,name=logical_pool_id,json=logicalPoolId,proto3" json:"logical_pool_id,omitempty"`
	PoolGeneration            uint64                 `protobuf:"varint,3,opt,name=pool_generation,json=poolGeneration,proto3" json:"pool_generation,omitempty"`
	ModelControlIncarnationId string                 `protobuf:"bytes,4,opt,name=model_control_incarnation_id,json=modelControlIncarnationId,proto3" json:"model_control_incarnation_id,omitempty"`
	OperationId               string                 `protobuf:"bytes,5,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Scope                     string                 `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	BindingGeneration         uint64                 `protobuf:"varint,7,opt,name=binding_generation,json=bindingGeneration,proto3" json:"binding_generation,omitempty"`
	ModelRevisionId           string                 `protobuf:"bytes,8,opt,name=model_revision_id,json=modelRevisionId,proto3" json:"model_revision_id,omitempty"`
	StartupEnvelopeDigest     string                 `protobuf:"bytes,9,opt,name=startup_envelope_digest,json=startupEnvelopeDigest,proto3" json:"startup_envelope_digest,omitempty"`
	PoolObservationDigest     string                 `protobuf:"bytes,10,opt,name=pool_observation_digest,json=poolObservationDigest,proto3" json:"pool_observation_digest,omitempty"`
	BindingDigest             string                 `protobuf:"bytes,11,opt,name=binding_digest,json=bindingDigest,proto3" json:"binding_digest,omitempty"`
	MinReadyReplicas          uint32                 `protobuf:"varint,12,opt,name=min_ready_replicas,json=minReadyReplicas,proto3" json:"min_ready_replicas,omitempty"`
	ModelRevisionDigest       string                 `protobuf:"bytes,13,opt,name=model_revision_digest,json=modelRevisionDigest,proto3" json:"model_revision_digest,omitempty"`
	ModelBundleDigest         string                 `protobuf:"bytes,14,opt,name=model_bundle_digest,json=modelBundleDigest,proto3" json:"model_bundle_digest,omitempty"`
	FeatureContractDigest     string                 `protobuf:"bytes,15,opt,name=feature_contract_digest,json=featureContractDigest,proto3" json:"feature_contract_digest,omitempty"`
	LabelContractDigest       string                 `protobuf:"bytes,16,opt,name=label_contract_digest,json=labelContractDigest,proto3" json:"label_contract_digest,omitempty"`
	OutputAdapterDigest       string                 `protobuf:"bytes,17,opt,name=output_adapter_digest,json=outputAdapterDigest,proto3" json:"output_adapter_digest,omitempty"`
	WireProfileDigest         string                 `protobuf:"bytes,18,opt,name=wire_profile_digest,json=wireProfileDigest,proto3" json:"wire_profile_digest,omitempty"`
	RuntimeProfileDigest      string                 `protobuf:"bytes,19,opt,name=runtime_profile_digest,json=runtimeProfileDigest,proto3" json:"runtime_profile_digest,omitempty"`
	OptimizationProfileDigest string                 `protobuf:"bytes,20,opt,name=optimization_profile_digest,json=optimizationProfileDigest,proto3" json:"optimization_profile_digest,omitempty"`
	WireProfile               string                 `protobuf:"bytes,21,opt,name=wire_profile,json=wireProfile,proto3" json:"wire_profile,omitempty"`
	RuntimeProfile            string                 `protobuf:"bytes,22,opt,name=runtime_profile,json=runtimeProfile,proto3" json:"runtime_profile,omitempty"`
	AvailabilityProfile       string                 `protobuf:"bytes,23,opt,name=availability_profile,json=availabilityProfile,proto3" json:"availability_profile,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PoolGenerationRequest) Reset() {
	*x = PoolGenerationRequest{}
	mi := &file_control_adapter_v1_control_adapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolGenerationRequest) ProtoMessage() {}

func (x *PoolGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_adapter_v1_control_adapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolGenerationRequest.ProtoReflect.Descriptor instead.
func (*PoolGenerationRequest) Descriptor() ([]byte, []int) {
	return file_control_adapter_v1_control_adapter_proto_rawDescGZIP(), []int{0}
}

func (x *PoolGenerationRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *PoolGenerationRequest) GetLogicalPoolId() string {
	if x != nil {
		return x.LogicalPoolId
	}
	return ""
}

func (x *PoolGenerationRequest) GetPoolGeneration() uint64 {
	if x != nil {
		return x.PoolGeneration
	}
	return 0
}

func (x *PoolGenerationRequest) GetModelControlIncarnationId() string {
	if x != nil {
		return x.ModelControlIncarnationId
	}
	return ""
}

func (x *PoolGenerationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *PoolGenerationRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *PoolGenerationRequest) GetBindingGeneration() uint64 {
	if x != nil {
		return x.BindingGeneration
	}
	return 0
}

func (x *PoolGenerationRequest) GetModelRevisionId() string {
	if x != nil {
		return x.ModelRevisionId
	}
	return ""
}

func (x *PoolGenerationRequest) GetStartupEnvelopeDigest() string {
	if x != nil {
		return x.StartupEnvelopeDigest
	}
	return ""
}

func (x *PoolGenerationRequest) GetPoolObservationDigest() string {
	if x != nil {
		return x.PoolObservationDigest
	}
	return ""
}

func (x *PoolGenerationRequest) GetBindingDigest() string {
	if x != nil {
		return x.BindingDigest
	}
	return ""
}

func (x *PoolGenerationRequest) GetMinReadyReplicas() uint32 {
	if x != nil {
		return x.MinReadyReplicas
	}
	return 0
}

func (x *PoolGenerationRequest) GetModelRevisionDigest() string {
	if x != nil {
		return x.ModelRevisionDigest
	}
	return ""
}

func (x *PoolGenerationRequest) GetModelBundleDigest() string {
	if x != nil {
		return x.ModelBundleDigest
	}
	return ""
}

func (x *PoolGenerationRequest) GetFeatureContractDigest() string {
	if x != nil {
		return x.FeatureContractDigest
	}
	return ""
}

func (x *PoolGenerationRequest) GetLabelContractDigest() string {
	if x != nil {
		return x.LabelContractDigest
	}
	return ""
}

func (x *PoolGenerationRequest) GetOutputAdapterDigest() string {
	if x != nil {
		return x.OutputAdapterDigest
	}
	return ""
}

func (x *PoolGenerationRequest) GetWireProfileDigest() string {
	if x != nil {
		return x.WireProfileDigest
	}
	return ""
}

func (x *PoolGenerationRequest) GetRuntimeProfileDigest() string {
	if x != nil {
		return x.RuntimeProfileDigest
	}
	return ""
}

func (x *PoolGenerationRequest) GetOptimizationProfileDigest() string {
	if x != nil {
		return x.OptimizationProfileDigest
	}
	return ""
}

func (x *PoolGenerationRequest) GetWireProfile() string {
	if x != nil {
		return x.WireProfile
	}
	return ""
}

func (x *PoolGenerationRequest) GetRuntimeProfile() string {
	if x != nil {
		return x.RuntimeProfile
	}
	return ""
}

func (x *PoolGenerationRequest) GetAvailabilityProfile() string {
	if x != nil {
		return x.AvailabilityProfile
	}
	return ""
}

type DeploymentActionReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion  string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	LogicalPoolId  string                 `protobuf:"bytes,2,opt,name=logical_pool_id,json=logicalPoolId,proto3" json:"logical_pool_id,omitempty"`
	PoolGeneration uint64                 `protobuf:"varint,3,opt,name=pool_generation,json=poolGeneration,proto3" json:"pool_generation,omitempty"`
	OperationId    string                 `protobuf:"bytes,4,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Action         string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	ActionDigest   string                 `protobuf:"bytes,6,opt,name=action_digest,json=actionDigest,proto3" json:"action_digest,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ReasonCode     string                 `protobuf:"bytes,8,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	TraceId        string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeploymentActionReply) Reset() {
	*x = DeploymentActionReply{}
	mi := &file_control_adapter_v1_control_adapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentActionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentActionReply) ProtoMessage() {}

func (x *DeploymentActionReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_adapter_v1_control_adapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentActionReply.ProtoReflect.Descriptor instead.
func (*DeploymentActionReply) Descriptor() ([]byte, []int) {
	return file_control_adapter_v1_control_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *DeploymentActionReply) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *DeploymentActionReply) GetLogicalPoolId() string {
	if x != nil {
		return x.LogicalPoolId
	}
	return ""
}

func (x *DeploymentActionReply) GetPoolGeneration() uint64 {
	if x != nil {
		return x.PoolGeneration
	}
	return 0
}

func (x *DeploymentActionReply) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *DeploymentActionReply) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DeploymentActionReply) GetActionDigest() string {
	if x != nil {
		return x.ActionDigest
	}
	return ""
}

func (x *DeploymentActionReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeploymentActionReply) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *DeploymentActionReply) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type WorkerIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	WorkerDigest  string                 `protobuf:"bytes,2,opt,name=worker_digest,json=workerDigest,proto3" json:"worker_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerIdentity) Reset() {
	*x = WorkerIdentity{}
	mi := &file_control_adapter_v1_control_adapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerIdentity) ProtoMessage() {}

func (x *WorkerIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_control_adapter_v1_control_adapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerIdentity.ProtoReflect.Descriptor instead.
func (*WorkerIdentity) Descriptor() ([]byte, []int) {
	return file_control_adapter_v1_control_adapter_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerIdentity) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerIdentity) GetWorkerDigest() string {
	if x != nil {
		return x.WorkerDigest
	}
	return ""
}

type PoolReadback struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion             string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	LogicalPoolId             string                 `protobuf:"bytes,2,opt,name=logical_pool_id,json=logicalPoolId,proto3" json:"logical_pool_id,omitempty"`
	PoolGeneration            uint64                 `protobuf:"varint,3,opt,name=pool_generation,json=poolGeneration,proto3" json:"pool_generation,omitempty"`
	BindingGeneration         uint64                 `protobuf:"varint,4,opt,name=binding_generation,json=bindingGeneration,proto3" json:"binding_generation,omitempty"`
	ModelControlIncarnationId string                 `protobuf:"bytes,5,opt,name=model_control_incarnation_id,json=modelControlIncarnationId,proto3" json:"model_control_incarnation_id,omitempty"`
	OperationId               string                 `protobuf:"bytes,6,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ModelRevisionDigest       string                 `protobuf:"bytes,7,opt,name=model_revision_digest,json=modelRevisionDigest,proto3" json:"model_revision_digest,omitempty"`
	ModelBundleDigest         string                 `protobuf:"bytes,8,opt,name=model_bundle_digest,json=modelBundleDigest,proto3" json:"model_bundle_digest,omitempty"`
	FeatureContractDigest     string                 `protobuf:"bytes,9,opt,name=feature_contract_digest,json=featureContractDigest,proto3" json:"feature_contract_digest,omitempty"`
	LabelContractDigest       string                 `protobuf:"bytes,10,opt,name=label_contract_digest,json=labelContractDigest,proto3" json:"label_contract_digest,omitempty"`
	OutputAdapterDigest       string                 `protobuf:"bytes,11,opt,name=output_adapter_digest,json=outputAdapterDigest,proto3" json:"output_adapter_digest,omitempty"`
	WireProfileDigest         string                 `protobuf:"bytes,12,opt,name=wire_profile_digest,json=wireProfileDigest,proto3" json:"wire_profile_digest,omitempty"`
	RuntimeProfileDigest      string                 `protobuf:"bytes,13,opt,name=runtime_profile_digest,json=runtimeProfileDigest,proto3" json:"runtime_profile_digest,omitempty"`
	OptimizationProfileDigest string                 `protobuf:"bytes,14,opt,name=optimization_profile_digest,json=optimizationProfileDigest,proto3" json:"optimization_profile_digest,omitempty"`
	WireProfile               string                 `protobuf:"bytes,15,opt,name=wire_profile,json=wireProfile,proto3" json:"wire_profile,omitempty"`
	RuntimeProfile            string                 `protobuf:"bytes,16,opt,name=runtime_profile,json=runtimeProfile,proto3" json:"runtime_profile,omitempty"`
	AvailabilityProfile       string                 `protobuf:"bytes,17,opt,name=availability_profile,json=availabilityProfile,proto3" json:"availability_profile,omitempty"`
	ReadyReplicas             uint32                 `protobuf:"varint,18,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	ReadbackAttemptId         string                 `protobuf:"bytes,19,opt,name=readback_attempt_id,json=readbackAttemptId,proto3" json:"readback_attempt_id,omitempty"`
	ObservedAtUnixMs          int64                  `protobuf:"varint,20,opt,name=observed_at_unix_ms,json=observedAtUnixMs,proto3" json:"observed_at_unix_ms,omitempty"`
	StartupEnvelopeDigest     string                 `protobuf:"bytes,21,opt,name=startup_envelope_digest,json=startupEnvelopeDigest,proto3" json:"startup_envelope_digest,omitempty"`
	PoolObservationDigest     string                 `protobuf:"bytes,22,opt,name=pool_observation_digest,json=poolObservationDigest,proto3" json:"pool_observation_digest,omitempty"`
	BindingDigest             string                 `protobuf:"bytes,23,opt,name=binding_digest,json=bindingDigest,proto3" json:"binding_digest,omitempty"`
	Endpoint                  string                 `protobuf:"bytes,24,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	TlsServerName             string                 `protobuf:"bytes,25,opt,name=tls_server_name,json=tlsServerName,proto3" json:"tls_server_name,omitempty"`
	TlsIdentityRef            string                 `protobuf:"bytes,26,opt,name=tls_identity_ref,json=tlsIdentityRef,proto3" json:"tls_identity_ref,omitempty"`
	EligibleWorkers           []*WorkerIdentity      `protobuf:"bytes,27,rep,name=eligible_workers,json=eligibleWorkers,proto3" json:"eligible_workers,omitempty"`
	Loaded                    bool                   `protobuf:"varint,28,opt,name=loaded,proto3" json:"loaded,omitempty"`
	ReadbackDigest            string                 `protobuf:"bytes,29,opt,name=readback_digest,json=readbackDigest,proto3" json:"readback_digest,omitempty"`
	ReasonCode                string                 `protobuf:"bytes,30,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	TraceId                   string                 `protobuf:"bytes,31,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PoolReadback) Reset() {
	*x = PoolReadback{}
	mi := &file_control_adapter_v1_control_adapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolReadback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolReadback) ProtoMessage() {}

func (x *PoolReadback) ProtoReflect() protoreflect.Message {
	mi := &file_control_adapter_v1_control_adapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolReadback.ProtoReflect.Descriptor instead.
func (*PoolReadback) Descriptor() ([]byte, []int) {
	return file_control_adapter_v1_control_adapter_proto_rawDescGZIP(), []int{3}
}

func (x *PoolReadback) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *PoolReadback) GetLogicalPoolId() string {
	if x != nil {
		return x.LogicalPoolId
	}
	return ""
}

func (x *PoolReadback) GetPoolGeneration() uint64 {
	if x != nil {
		return x.PoolGeneration
	}
	return 0
}

func (x *PoolReadback) GetBindingGeneration() uint64 {
	if x != nil {
		return x.BindingGeneration
	}
	return 0
}

func (x *PoolReadback) GetModelControlIncarnationId() string {
	if x != nil {
		return x.ModelControlIncarnationId
	}
	return ""
}

func (x *PoolReadback) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *PoolReadback) GetModelRevisionDigest() string {
	if x != nil {
		return x.ModelRevisionDigest
	}
	return ""
}

func (x *PoolReadback) GetModelBundleDigest() string {
	if x != nil {
		return x.ModelBundleDigest
	}
	return ""
}

func (x *PoolReadback) GetFeatureContractDigest() string {
	if x != nil {
		return x.FeatureContractDigest
	}
	return ""
}

func (x *PoolReadback) GetLabelContractDigest() string {
	if x != nil {
		return x.LabelContractDigest
	}
	return ""
}

func (x *PoolReadback) GetOutputAdapterDigest() string {
	if x != nil {
		return x.OutputAdapterDigest
	}
	return ""
}

func (x *PoolReadback) GetWireProfileDigest() string {
	if x != nil {
		return x.WireProfileDigest
	}
	return ""
}

func (x *PoolReadback) GetRuntimeProfileDigest() string {
	if x != nil {
		return x.RuntimeProfileDigest
	}
	return ""
}

func (x *PoolReadback) GetOptimizationProfileDigest() string {
	if x != nil {
		return x.OptimizationProfileDigest
	}
	return ""
}

func (x *PoolReadback) GetWireProfile() string {
	if x != nil {
		return x.WireProfile
	}
	return ""
}

func (x *PoolReadback) GetRuntimeProfile() string {
	if x != nil {
		return x.RuntimeProfile
	}
	return ""
}

func (x *PoolReadback) GetAvailabilityProfile() string {
	if x != nil {
		return x.AvailabilityProfile
	}
	return ""
}

func (x *PoolReadback) GetReadyReplicas() uint32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *PoolReadback) GetReadbackAttemptId() string {
	if x != nil {
		return x.ReadbackAttemptId
	}
	return ""
}

func (x *PoolReadback) GetObservedAtUnixMs() int64 {
	if x != nil {
		return x.ObservedAtUnixMs
	}
	return 0
}

func (x *PoolReadback) GetStartupEnvelopeDigest() string {
	if x != nil {
		return x.StartupEnvelopeDigest
	}
	return ""
}

func (x *PoolReadback) GetPoolObservationDigest() string {
	if x != nil {
		return x.PoolObservationDigest
	}
	return ""
}

func (x *PoolReadback) GetBindingDigest() string {
	if x != nil {
		return x.BindingDigest
	}
	return ""
}

func (x *PoolReadback) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PoolReadback) GetTlsServerName() string {
	if x != nil {
		return x.TlsServerName
	}
	return ""
}

func (x *PoolReadback) GetTlsIdentityRef() string {
	if x != nil {
		return x.TlsIdentityRef
	}
	return ""
}

func (x *PoolReadback) GetEligibleWorkers() []*WorkerIdentity {
	if x != nil {
		return x.EligibleWorkers
	}
	return nil
}

func (x *PoolReadback) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *PoolReadback) GetReadbackDigest() string {
	if x != nil {
		return x.ReadbackDigest
	}
	return ""
}

func (x *PoolReadback) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *PoolReadback) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type CapacityReadback struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion    string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	LogicalPoolId    string                 `protobuf:"bytes,2,opt,name=logical_pool_id,json=logicalPoolId,proto3" json:"logical_pool_id,omitempty"`
	PoolGeneration   uint64                 `protobuf:"varint,3,opt,name=pool_generation,json=poolGeneration,proto3" json:"pool_generation,omitempty"`
	Qualified        bool                   `protobuf:"varint,4,opt,name=qualified,proto3" json:"qualified,omitempty"`
	MinReadyMet      bool                   `protobuf:"varint,5,opt,name=min_ready_met,json=minReadyMet,proto3" json:"min_ready_met,omitempty"`
	FailureDomain    string                 `protobuf:"bytes,6,opt,name=failure_domain,json=failureDomain,proto3" json:"failure_domain,omitempty"`
	ReasonCode       string                 `protobuf:"bytes,7,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	CapacityDigest   string                 `protobuf:"bytes,8,opt,name=capacity_digest,json=capacityDigest,proto3" json:"capacity_digest,omitempty"`
	ObservedAtUnixMs int64                  `protobuf:"varint,9,opt,name=observed_at_unix_ms,json=observedAtUnixMs,proto3" json:"observed_at_unix_ms,omitempty"`
	TraceId          string                 `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CapacityReadback) Reset() {
	*x = CapacityReadback{}
	mi := &file_control_adapter_v1_control_adapter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityReadback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityReadback) ProtoMessage() {}

func (x *CapacityReadback) ProtoReflect() protoreflect.Message {
	mi := &file_control_adapter_v1_control_adapter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityReadback.ProtoReflect.Descriptor instead.
func (*CapacityReadback) Descriptor() ([]byte, []int) {
	return file_control_adapter_v1_control_adapter_proto_rawDescGZIP(), []int{4}
}

func (x *CapacityReadback) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *CapacityReadback) GetLogicalPoolId() string {
	if x != nil {
		return x.LogicalPoolId
	}
	return ""
}

func (x *CapacityReadback) GetPoolGeneration() uint64 {
	if x != nil {
		return x.PoolGeneration
	}
	return 0
}

func (x *CapacityReadback) GetQualified() bool {
	if x != nil {
		return x.Qualified
	}
	return false
}

func (x *CapacityReadback) GetMinReadyMet() bool {
	if x != nil {
		return x.MinReadyMet
	}
	return false
}

func (x *CapacityReadback) GetFailureDomain() string {
	if x != nil {
		return x.FailureDomain
	}
	return ""
}

func (x *CapacityReadback) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *CapacityReadback) GetCapacityDigest() string {
	if x != nil {
		return x.CapacityDigest
	}
	return ""
}

func (x *CapacityReadback) GetObservedAtUnixMs() int64 {
	if x != nil {
		return x.ObservedAtUnixMs
	}
	return 0
}

func (x *CapacityReadback) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type StatisticsExecutionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion     string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RunId             string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	LeaseId           string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	ClaimGeneration   uint64                 `protobuf:"varint,4,opt,name=claim_generation,json=claimGeneration,proto3" json:"claim_generation,omitempty"`
	ResultFence       string                 `protobuf:"bytes,5,opt,name=result_fence,json=resultFence,proto3" json:"result_fence,omitempty"`
	BindingGeneration uint64                 `protobuf:"varint,6,opt,name=binding_generation,json=bindingGeneration,proto3" json:"binding_generation,omitempty"`
	DefinitionId      string                 `protobuf:"bytes,7,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	DefinitionDigest  string                 `protobuf:"bytes,8,opt,name=definition_digest,json=definitionDigest,proto3" json:"definition_digest,omitempty"`
	Scope             string                 `protobuf:"bytes,9,opt,name=scope,proto3" json:"scope,omitempty"`
	ExpiresAtUnixMs   int64                  `protobuf:"varint,10,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	DeadlineMs        uint32                 `protobuf:"varint,11,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	InputBundleJson   []byte                 `protobuf:"bytes,12,opt,name=input_bundle_json,json=inputBundleJson,proto3" json:"input_bundle_json,omitempty"`
	FrozenInputDigest string                 `protobuf:"bytes,13,opt,name=frozen_input_digest,json=frozenInputDigest,proto3" json:"frozen_input_digest,omitempty"`
	TraceId           string                 `protobuf:"bytes,14,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatisticsExecutionRequest) Reset() {
	*x = StatisticsExecutionRequest{}
	mi := &file_control_adapter_v1_control_adapter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsExecutionRequest) ProtoMessage() {}

func (x *StatisticsExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_adapter_v1_control_adapter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsExecutionRequest.ProtoReflect.Descriptor instead.
func (*StatisticsExecutionRequest) Descriptor() ([]byte, []int) {
	return file_control_adapter_v1_control_adapter_proto_rawDescGZIP(), []int{5}
}

func (x *StatisticsExecutionRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *StatisticsExecutionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StatisticsExecutionRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *StatisticsExecutionRequest) GetClaimGeneration() uint64 {
	if x != nil {
		return x.ClaimGeneration
	}
	return 0
}

func (x *StatisticsExecutionRequest) GetResultFence() string {
	if x != nil {
		return x.ResultFence
	}
	return ""
}

func (x *StatisticsExecutionRequest) GetBindingGeneration() uint64 {
	if x != nil {
		return x.BindingGeneration
	}
	return 0
}

func (x *StatisticsExecutionRequest) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

func (x *StatisticsExecutionRequest) GetDefinitionDigest() string {
	if x != nil {
		return x.DefinitionDigest
	}
	return ""
}

func (x *StatisticsExecutionRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *StatisticsExecutionRequest) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

func (x *StatisticsExecutionRequest) GetDeadlineMs() uint32 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

func (x *StatisticsExecutionRequest) GetInputBundleJson() []byte {
	if x != nil {
		return x.InputBundleJson
	}
	return nil
}

func (x *StatisticsExecutionRequest) GetFrozenInputDigest() string {
	if x != nil {
		return x.FrozenInputDigest
	}
	return ""
}

func (x *StatisticsExecutionRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type StatisticsExecutionReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion  string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RunId          string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ResultFence    string                 `protobuf:"bytes,3,opt,name=result_fence,json=resultFence,proto3" json:"result_fence,omitempty"`
	ArtifactJson   []byte                 `protobuf:"bytes,4,opt,name=artifact_json,json=artifactJson,proto3" json:"artifact_json,omitempty"`
	ArtifactDigest string                 `protobuf:"bytes,5,opt,name=artifact_digest,json=artifactDigest,proto3" json:"artifact_digest,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	ReasonCode     string                 `protobuf:"bytes,7,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	TraceId        string                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatisticsExecutionReply) Reset() {
	*x = StatisticsExecutionReply{}
	mi := &file_control_adapter_v1_control_adapter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsExecutionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsExecutionReply) ProtoMessage() {}

func (x *StatisticsExecutionReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_adapter_v1_control_adapter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsExecutionReply.ProtoReflect.Descriptor instead.
func (*StatisticsExecutionReply) Descriptor() ([]byte, []int) {
	return file_control_adapter_v1_control_adapter_proto_rawDescGZIP(), []int{6}
}

func (x *StatisticsExecutionReply) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *StatisticsExecutionReply) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StatisticsExecutionReply) GetResultFence() string {
	if x != nil {
		return x.ResultFence
	}
	return ""
}

func (x *StatisticsExecutionReply) GetArtifactJson() []byte {
	if x != nil {
		return x.ArtifactJson
	}
	return nil
}

func (x *StatisticsExecutionReply) GetArtifactDigest() string {
	if x != nil {
		return x.ArtifactDigest
	}
	return ""
}

func (x *StatisticsExecutionReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatisticsExecutionReply) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *StatisticsExecutionReply) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_control_adapter_v1_control_adapter_proto protoreflect.FileDescriptor

const file_control_adapter_v1_control_adapter_proto_rawDesc = "" +
	"\n" +
	"(control-adapter/v1/control_adapter.proto\x12\x17masi.control.adapter.v1\"\xd2\b\n" +
	"\x15PoolGenerationRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12&\n" +
	"\x0flogical_pool_id\x18\x02 \x01(\tR\rlogicalPoolId\x12'\n" +
	"\x0fpool_generation\x18\x03 \x01(\x04R\x0epoolGeneration\x12?\n" +
	"\x1cmodel_control_incarnation_id\x18\x04 \x01(\tR\x19modelControlIncarnationId\x12!\n" +
	"\foperation_id\x18\x05 \x01(\tR\voperationId\x12\x14\n" +
	"\x05scope\x18\x06 \x01(\tR\x05scope\x12-\n" +
	"\x12binding_generation\x18\a \x01(\x04R\x11bindingGeneration\x12*\n" +
	"\x11model_revision_id\x18\b \x01(\tR\x0fmodelRevisionId\x126\n" +
	"\x17startup_envelope_digest\x18\t \x01(\tR\x15startupEnvelopeDigest\x126\n" +
	"\x17pool_observation_digest\x18\n" +
	" \x01(\tR\x15poolObservationDigest\x12%\n" +
	"\x0ebinding_digest\x18\v \x01(\tR\rbindingDigest\x12,\n" +
	"\x12min_ready_replicas\x18\f \x01(\rR\x10minReadyReplicas\x122\n" +
	"\x15model_revision_digest\x18\r \x01(\tR\x13modelRevisionDigest\x12.\n" +
	"\x13model_bundle_digest\x18\x0e \x01(\tR\x11modelBundleDigest\x126\n" +
	"\x17feature_contract_digest\x18\x0f \x01(\tR\x15featureContractDigest\x122\n" +
	"\x15label_contract_digest\x18\x10 \x01(\tR\x13labelContractDigest\x122\n" +
	"\x15output_adapter_digest\x18\x11 \x01(\tR\x13outputAdapterDigest\x12.\n" +
	"\x13wire_profile_digest\x18\x12 \x01(\tR\x11wireProfileDigest\x124\n" +
	"\x16runtime_profile_digest\x18\x13 \x01(\tR\x14runtimeProfileDigest\x12>\n" +
	"\x1boptimization_profile_digest\x18\x14 \x01(\tR\x19optimizationProfileDigest\x12!\n" +
	"\fwire_profile\x18\x15 \x01(\tR\vwireProfile\x12'\n" +
	"\x0fruntime_profile\x18\x16 \x01(\tR\x0eruntimeProfile\x121\n" +
	"\x14availability_profile\x18\x17 \x01(\tR\x13availabilityProfile\"\xc3\x02\n" +
	"\x15DeploymentActionReply\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12&\n" +
	"\x0flogical_pool_id\x18\x02 \x01(\tR\rlogicalPoolId\x12'\n" +
	"\x0fpool_generation\x18\x03 \x01(\x04R\x0epoolGeneration\x12!\n" +
	"\foperation_id\x18\x04 \x01(\tR\voperationId\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12#\n" +
	"\raction_digest\x18\x06 \x01(\tR\factionDigest\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\vreason_code\x18\b \x01(\tR\n" +
	"reasonCode\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\"R\n" +
	"\x0eWorkerIdentity\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12#\n" +
	"\rworker_digest\x18\x02 \x01(\tR\fworkerDigest\"\x9e\v\n" +
	"\fPoolReadback\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12&\n" +
	"\x0flogical_pool_id\x18\x02 \x01(\tR\rlogicalPoolId\x12'\n" +
	"\x0fpool_generation\x18\x03 \x01(\x04R\x0epoolGeneration\x12-\n" +
	"\x12binding_generation\x18\x04 \x01(\x04R\x11bindingGeneration\x12?\n" +
	"\x1cmodel_control_incarnation_id\x18\x05 \x01(\tR\x19modelControlIncarnationId\x12!\n" +
	"\foperation_id\x18\x06 \x01(\tR\voperationId\x122\n" +
	"\x15model_revision_digest\x18\a \x01(\tR\x13modelRevisionDigest\x12.\n" +
	"\x13model_bundle_digest\x18\b \x01(\tR\x11modelBundleDigest\x126\n" +
	"\x17feature_contract_digest\x18\t \x01(\tR\x15featureContractDigest\x122\n" +
	"\x15label_contract_digest\x18\n" +
	" \x01(\tR\x13labelContractDigest\x122\n" +
	"\x15output_adapter_digest\x18\v \x01(\tR\x13outputAdapterDigest\x12.\n" +
	"\x13wire_profile_digest\x18\f \x01(\tR\x11wireProfileDigest\x124\n" +
	"\x16runtime_profile_digest\x18\r \x01(\tR\x14runtimeProfileDigest\x12>\n" +
	"\x1boptimization_profile_digest\x18\x0e \x01(\tR\x19optimizationProfileDigest\x12!\n" +
	"\fwire_profile\x18\x0f \x01(\tR\vwireProfile\x12'\n" +
	"\x0fruntime_profile\x18\x10 \x01(\tR\x0eruntimeProfile\x121\n" +
	"\x14availability_profile\x18\x11 \x01(\tR\x13availabilityProfile\x12%\n" +
	"\x0eready_replicas\x18\x12 \x01(\rR\rreadyReplicas\x12.\n" +
	"\x13readback_attempt_id\x18\x13 \x01(\tR\x11readbackAttemptId\x12-\n" +
	"\x13observed_at_unix_ms\x18\x14 \x01(\x03R\x10observedAtUnixMs\x126\n" +
	"\x17startup_envelope_digest\x18\x15 \x01(\tR\x15startupEnvelopeDigest\x126\n" +
	"\x17pool_observation_digest\x18\x16 \x01(\tR\x15poolObservationDigest\x12%\n" +
	"\x0ebinding_digest\x18\x17 \x01(\tR\rbindingDigest\x12\x1a\n" +
	"\bendpoint\x18\x18 \x01(\tR\bendpoint\x12&\n" +
	"\x0ftls_server_name\x18\x19 \x01(\tR\rtlsServerName\x12(\n" +
	"\x10tls_identity_ref\x18\x1a \x01(\tR\x0etlsIdentityRef\x12R\n" +
	"\x10eligible_workers\x18\x1b \x03(\v2'.masi.control.adapter.v1.WorkerIdentityR\x0feligibleWorkers\x12\x16\n" +
	"\x06loaded\x18\x1c \x01(\bR\x06loaded\x12'\n" +
	"\x0freadback_digest\x18\x1d \x01(\tR\x0ereadbackDigest\x12\x1f\n" +
	"\vreason_code\x18\x1e \x01(\tR\n" +
	"reasonCode\x12\x19\n" +
	"\btrace_id\x18\x1f \x01(\tR\atraceId\"\x87\x03\n" +
	"\x10CapacityReadback\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12&\n" +
	"\x0flogical_pool_id\x18\x02 \x01(\tR\rlogicalPoolId\x12'\n" +
	"\x0fpool_generation\x18\x03 \x01(\x04R\x0epoolGeneration\x12\x1c\n" +
	"\tqualified\x18\x04 \x01(\bR\tqualified\x12\"\n" +
	"\rmin_ready_met\x18\x05 \x01(\bR\vminReadyMet\x12%\n" +
	"\x0efailure_domain\x18\x06 \x01(\tR\rfailureDomain\x12\x1f\n" +
	"\vreason_code\x18\a \x01(\tR\n" +
	"reasonCode\x12'\n" +
	"\x0fcapacity_digest\x18\b \x01(\tR\x0ecapacityDigest\x12-\n" +
	"\x13observed_at_unix_ms\x18\t \x01(\x03R\x10observedAtUnixMs\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\"\x9f\x04\n" +
	"\x1aStatisticsExecutionRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\x12)\n" +
	"\x10claim_generation\x18\x04 \x01(\x04R\x0fclaimGeneration\x12!\n" +
	"\fresult_fence\x18\x05 \x01(\tR\vresultFence\x12-\n" +
	"\x12binding_generation\x18\x06 \x01(\x04R\x11bindingGeneration\x12#\n" +
	"\rdefinition_id\x18\a \x01(\tR\fdefinitionId\x12+\n" +
	"\x11definition_digest\x18\b \x01(\tR\x10definitionDigest\x12\x14\n" +
	"\x05scope\x18\t \x01(\tR\x05scope\x12+\n" +
	"\x12expires_at_unix_ms\x18\n" +
	" \x01(\x03R\x0fexpiresAtUnixMs\x12\x1f\n" +
	"\vdeadline_ms\x18\v \x01(\rR\n" +
	"deadlineMs\x12*\n" +
	"\x11input_bundle_json\x18\f \x01(\fR\x0finputBundleJson\x12.\n" +
	"\x13frozen_input_digest\x18\r \x01(\tR\x11frozenInputDigest\x12\x19\n" +
	"\btrace_id\x18\x0e \x01(\tR\atraceId\"\x9d\x02\n" +
	"\x18StatisticsExecutionReply\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12!\n" +
	"\fresult_fence\x18\x03 \x01(\tR\vresultFence\x12#\n" +
	"\rartifact_json\x18\x04 \x01(\fR\fartifactJson\x12'\n" +
	"\x0fartifact_digest\x18\x05 \x01(\tR\x0eartifactDigest\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vreason_code\x18\a \x01(\tR\n" +
	"reasonCode\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId2\xd8\x02\n" +
	"\x11DeploymentAdapter\x12k\n" +
	"\tStagePool\x12..masi.control.adapter.v1.PoolGenerationRequest\x1a..masi.control.adapter.v1.DeploymentActionReply\x12f\n" +
	"\rStartReplicas\x12..masi.control.adapter.v1.PoolGenerationRequest\x1a%.masi.control.adapter.v1.PoolReadback\x12n\n" +
	"\x11WarmupAndCapacity\x12..masi.control.adapter.v1.PoolGenerationRequest\x1a).masi.control.adapter.v1.CapacityReadback2\x97\x01\n" +
	"\x18PluginStatisticsExecutor\x12{\n" +
	"\x11ExecuteStatistics\x123.masi.control.adapter.v1.StatisticsExecutionRequest\x1a1.masi.control.adapter.v1.StatisticsExecutionReplyB8Z6masi-nids/control-go/internal/grpc/adapterv1;adapterv1b\x06proto3"

var (
	file_control_adapter_v1_control_adapter_proto_rawDescOnce sync.Once
	file_control_adapter_v1_control_adapter_proto_rawDescData []byte
)

func file_control_adapter_v1_control_adapter_proto_rawDescGZIP() []byte {
	file_control_adapter_v1_control_adapter_proto_rawDescOnce.Do(func() {
		file_control_adapter_v1_control_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_adapter_v1_control_adapter_proto_rawDesc), len(file_control_adapter_v1_control_adapter_proto_rawDesc)))
	})
	return file_control_adapter_v1_control_adapter_proto_rawDescData
}

var file_control_adapter_v1_control_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_control_adapter_v1_control_adapter_proto_goTypes = []any{
	(*PoolGenerationRequest)(nil),      // 0: masi.control.adapter.v1.PoolGenerationRequest
	(*DeploymentActionReply)(nil),      // 1: masi.control.adapter.v1.DeploymentActionReply
	(*WorkerIdentity)(nil),             // 2: masi.control.adapter.v1.WorkerIdentity
	(*PoolReadback)(nil),               // 3: masi.control.adapter.v1.PoolReadback
	(*CapacityReadback)(nil),           // 4: masi.control.adapter.v1.CapacityReadback
	(*StatisticsExecutionRequest)(nil), // 5: masi.control.adapter.v1.StatisticsExecutionRequest
	(*StatisticsExecutionReply)(nil),   // 6: masi.control.adapter.v1.StatisticsExecutionReply
}
var file_control_adapter_v1_control_adapter_proto_depIdxs = []int32{
	2, // 0: masi.control.adapter.v1.PoolReadback.eligible_workers:type_name -> masi.control.adapter.v1.WorkerIdentity
	0, // 1: masi.control.adapter.v1.DeploymentAdapter.StagePool:input_type -> masi.control.adapter.v1.PoolGenerationRequest
	0, // 2: masi.control.adapter.v1.DeploymentAdapter.StartReplicas:input_type -> masi.control.adapter.v1.PoolGenerationRequest
	0, // 3: masi.control.adapter.v1.DeploymentAdapter.WarmupAndCapacity:input_type -> masi.control.adapter.v1.PoolGenerationRequest
	5, // 4: masi.control.adapter.v1.PluginStatisticsExecutor.ExecuteStatistics:input_type -> masi.control.adapter.v1.StatisticsExecutionRequest
	1, // 5: masi.control.adapter.v1.DeploymentAdapter.StagePool:output_type -> masi.control.adapter.v1.DeploymentActionReply
	3, // 6: masi.control.adapter.v1.DeploymentAdapter.StartReplicas:output_type -> masi.control.adapter.v1.PoolReadback
	4, // 7: masi.control.adapter.v1.DeploymentAdapter.WarmupAndCapacity:output_type -> masi.control.adapter.v1.CapacityReadback
	6, // 8: masi.control.adapter.v1.PluginStatisticsExecutor.ExecuteStatistics:output_type -> masi.control.adapter.v1.StatisticsExecutionReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_control_adapter_v1_control_adapter_proto_init() }
func file_control_adapter_v1_control_adapter_proto_init() {
	if File_control_adapter_v1_control_adapter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_adapter_v1_control_adapter_proto_rawDesc), len(file_control_adapter_v1_control_adapter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_control_adapter_v1_control_adapter_proto_goTypes,
		DependencyIndexes: file_control_adapter_v1_control_adapter_proto_depIdxs,
		MessageInfos:      file_control_adapter_v1_control_adapter_proto_msgTypes,
	}.Build()
	File_control_adapter_v1_control_adapter_proto = out.File
	file_control_adapter_v1_control_adapter_proto_goTypes = nil
	file_control_adapter_v1_control_adapter_proto_depIdxs = nil
}
