// Public Edge Agent contracts. This file is the only source for generated
// Rust/Go/C++/Python/TypeScript adapters at the Edge boundaries.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: edge/v1/edge.proto

package edgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EdgeControl_AssignTarget_FullMethodName              = "/masi.edge.v1.EdgeControl/AssignTarget"
	EdgeControl_RenewTarget_FullMethodName               = "/masi.edge.v1.EdgeControl/RenewTarget"
	EdgeControl_RevokeTarget_FullMethodName              = "/masi.edge.v1.EdgeControl/RevokeTarget"
	EdgeControl_PreflightEffect_FullMethodName           = "/masi.edge.v1.EdgeControl/PreflightEffect"
	EdgeControl_ExecuteEffect_FullMethodName             = "/masi.edge.v1.EdgeControl/ExecuteEffect"
	EdgeControl_AcknowledgeEffect_FullMethodName         = "/masi.edge.v1.EdgeControl/AcknowledgeEffect"
	EdgeControl_PrepareRoute_FullMethodName              = "/masi.edge.v1.EdgeControl/PrepareRoute"
	EdgeControl_CommitRoute_FullMethodName               = "/masi.edge.v1.EdgeControl/CommitRoute"
	EdgeControl_ResumeRoute_FullMethodName               = "/masi.edge.v1.EdgeControl/ResumeRoute"
	EdgeControl_ConfigureRuleObservations_FullMethodName = "/masi.edge.v1.EdgeControl/ConfigureRuleObservations"
	EdgeControl_GetStatus_FullMethodName                 = "/masi.edge.v1.EdgeControl/GetStatus"
)

// EdgeControlClient is the client API for EdgeControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EdgeControlClient interface {
	AssignTarget(ctx context.Context, in *AssignTargetRequest, opts ...grpc.CallOption) (*TargetReply, error)
	RenewTarget(ctx context.Context, in *RenewTargetRequest, opts ...grpc.CallOption) (*TargetReply, error)
	RevokeTarget(ctx context.Context, in *RevokeTargetRequest, opts ...grpc.CallOption) (*TargetReply, error)
	PreflightEffect(ctx context.Context, in *PreflightEffectRequest, opts ...grpc.CallOption) (*PreflightEffectReply, error)
	ExecuteEffect(ctx context.Context, in *ExecuteEffectRequest, opts ...grpc.CallOption) (*EffectResult, error)
	AcknowledgeEffect(ctx context.Context, in *AcknowledgeEffectRequest, opts ...grpc.CallOption) (*PublishAck, error)
	PrepareRoute(ctx context.Context, in *PrepareRouteRequest, opts ...grpc.CallOption) (*RouteReply, error)
	CommitRoute(ctx context.Context, in *CommitRouteRequest, opts ...grpc.CallOption) (*RouteReply, error)
	ResumeRoute(ctx context.Context, in *ResumeRouteRequest, opts ...grpc.CallOption) (*RouteReply, error)
	ConfigureRuleObservations(ctx context.Context, in *ConfigureRuleObservationsRequest, opts ...grpc.CallOption) (*PublishAck, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*EdgeStatus, error)
}

type edgeControlClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeControlClient(cc grpc.ClientConnInterface) EdgeControlClient {
	return &edgeControlClient{cc}
}

func (c *edgeControlClient) AssignTarget(ctx context.Context, in *AssignTargetRequest, opts ...grpc.CallOption) (*TargetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetReply)
	err := c.cc.Invoke(ctx, EdgeControl_AssignTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeControlClient) RenewTarget(ctx context.Context, in *RenewTargetRequest, opts ...grpc.CallOption) (*TargetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetReply)
	err := c.cc.Invoke(ctx, EdgeControl_RenewTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeControlClient) RevokeTarget(ctx context.Context, in *RevokeTargetRequest, opts ...grpc.CallOption) (*TargetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetReply)
	err := c.cc.Invoke(ctx, EdgeControl_RevokeTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeControlClient) PreflightEffect(ctx context.Context, in *PreflightEffectRequest, opts ...grpc.CallOption) (*PreflightEffectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreflightEffectReply)
	err := c.cc.Invoke(ctx, EdgeControl_PreflightEffect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeControlClient) ExecuteEffect(ctx context.Context, in *ExecuteEffectRequest, opts ...grpc.CallOption) (*EffectResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EffectResult)
	err := c.cc.Invoke(ctx, EdgeControl_ExecuteEffect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeControlClient) AcknowledgeEffect(ctx context.Context, in *AcknowledgeEffectRequest, opts ...grpc.CallOption) (*PublishAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishAck)
	err := c.cc.Invoke(ctx, EdgeControl_AcknowledgeEffect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeControlClient) PrepareRoute(ctx context.Context, in *PrepareRouteRequest, opts ...grpc.CallOption) (*RouteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteReply)
	err := c.cc.Invoke(ctx, EdgeControl_PrepareRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeControlClient) CommitRoute(ctx context.Context, in *CommitRouteRequest, opts ...grpc.CallOption) (*RouteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteReply)
	err := c.cc.Invoke(ctx, EdgeControl_CommitRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeControlClient) ResumeRoute(ctx context.Context, in *ResumeRouteRequest, opts ...grpc.CallOption) (*RouteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteReply)
	err := c.cc.Invoke(ctx, EdgeControl_ResumeRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeControlClient) ConfigureRuleObservations(ctx context.Context, in *ConfigureRuleObservationsRequest, opts ...grpc.CallOption) (*PublishAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishAck)
	err := c.cc.Invoke(ctx, EdgeControl_ConfigureRuleObservations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeControlClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*EdgeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EdgeStatus)
	err := c.cc.Invoke(ctx, EdgeControl_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeControlServer is the server API for EdgeControl service.
// All implementations must embed UnimplementedEdgeControlServer
// for forward compatibility.
type EdgeControlServer interface {
	AssignTarget(context.Context, *AssignTargetRequest) (*TargetReply, error)
	RenewTarget(context.Context, *RenewTargetRequest) (*TargetReply, error)
	RevokeTarget(context.Context, *RevokeTargetRequest) (*TargetReply, error)
	PreflightEffect(context.Context, *PreflightEffectRequest) (*PreflightEffectReply, error)
	ExecuteEffect(context.Context, *ExecuteEffectRequest) (*EffectResult, error)
	AcknowledgeEffect(context.Context, *AcknowledgeEffectRequest) (*PublishAck, error)
	PrepareRoute(context.Context, *PrepareRouteRequest) (*RouteReply, error)
	CommitRoute(context.Context, *CommitRouteRequest) (*RouteReply, error)
	ResumeRoute(context.Context, *ResumeRouteRequest) (*RouteReply, error)
	ConfigureRuleObservations(context.Context, *ConfigureRuleObservationsRequest) (*PublishAck, error)
	GetStatus(context.Context, *GetStatusRequest) (*EdgeStatus, error)
	mustEmbedUnimplementedEdgeControlServer()
}

// UnimplementedEdgeControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEdgeControlServer struct{}

func (UnimplementedEdgeControlServer) AssignTarget(context.Context, *AssignTargetRequest) (*TargetReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignTarget not implemented")
}
func (UnimplementedEdgeControlServer) RenewTarget(context.Context, *RenewTargetRequest) (*TargetReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewTarget not implemented")
}
func (UnimplementedEdgeControlServer) RevokeTarget(context.Context, *RevokeTargetRequest) (*TargetReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeTarget not implemented")
}
func (UnimplementedEdgeControlServer) PreflightEffect(context.Context, *PreflightEffectRequest) (*PreflightEffectReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PreflightEffect not implemented")
}
func (UnimplementedEdgeControlServer) ExecuteEffect(context.Context, *ExecuteEffectRequest) (*EffectResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteEffect not implemented")
}
func (UnimplementedEdgeControlServer) AcknowledgeEffect(context.Context, *AcknowledgeEffectRequest) (*PublishAck, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeEffect not implemented")
}
func (UnimplementedEdgeControlServer) PrepareRoute(context.Context, *PrepareRouteRequest) (*RouteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareRoute not implemented")
}
func (UnimplementedEdgeControlServer) CommitRoute(context.Context, *CommitRouteRequest) (*RouteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitRoute not implemented")
}
func (UnimplementedEdgeControlServer) ResumeRoute(context.Context, *ResumeRouteRequest) (*RouteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeRoute not implemented")
}
func (UnimplementedEdgeControlServer) ConfigureRuleObservations(context.Context, *ConfigureRuleObservationsRequest) (*PublishAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureRuleObservations not implemented")
}
func (UnimplementedEdgeControlServer) GetStatus(context.Context, *GetStatusRequest) (*EdgeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedEdgeControlServer) mustEmbedUnimplementedEdgeControlServer() {}
func (UnimplementedEdgeControlServer) testEmbeddedByValue()                     {}

// UnsafeEdgeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EdgeControlServer will
// result in compilation errors.
type UnsafeEdgeControlServer interface {
	mustEmbedUnimplementedEdgeControlServer()
}

func RegisterEdgeControlServer(s grpc.ServiceRegistrar, srv EdgeControlServer) {
	// If the following call panics, it indicates UnimplementedEdgeControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EdgeControl_ServiceDesc, srv)
}

func _EdgeControl_AssignTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeControlServer).AssignTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeControl_AssignTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeControlServer).AssignTarget(ctx, req.(*AssignTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeControl_RenewTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeControlServer).RenewTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeControl_RenewTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeControlServer).RenewTarget(ctx, req.(*RenewTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeControl_RevokeTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeControlServer).RevokeTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeControl_RevokeTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeControlServer).RevokeTarget(ctx, req.(*RevokeTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeControl_PreflightEffect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreflightEffectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeControlServer).PreflightEffect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeControl_PreflightEffect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeControlServer).PreflightEffect(ctx, req.(*PreflightEffectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeControl_ExecuteEffect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteEffectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeControlServer).ExecuteEffect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeControl_ExecuteEffect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeControlServer).ExecuteEffect(ctx, req.(*ExecuteEffectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeControl_AcknowledgeEffect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeEffectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeControlServer).AcknowledgeEffect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeControl_AcknowledgeEffect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeControlServer).AcknowledgeEffect(ctx, req.(*AcknowledgeEffectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeControl_PrepareRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeControlServer).PrepareRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeControl_PrepareRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeControlServer).PrepareRoute(ctx, req.(*PrepareRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeControl_CommitRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeControlServer).CommitRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeControl_CommitRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeControlServer).CommitRoute(ctx, req.(*CommitRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeControl_ResumeRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeControlServer).ResumeRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeControl_ResumeRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeControlServer).ResumeRoute(ctx, req.(*ResumeRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeControl_ConfigureRuleObservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRuleObservationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeControlServer).ConfigureRuleObservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeControl_ConfigureRuleObservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeControlServer).ConfigureRuleObservations(ctx, req.(*ConfigureRuleObservationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeControl_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeControlServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeControl_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeControlServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EdgeControl_ServiceDesc is the grpc.ServiceDesc for EdgeControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EdgeControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "masi.edge.v1.EdgeControl",
	HandlerType: (*EdgeControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignTarget",
			Handler:    _EdgeControl_AssignTarget_Handler,
		},
		{
			MethodName: "RenewTarget",
			Handler:    _EdgeControl_RenewTarget_Handler,
		},
		{
			MethodName: "RevokeTarget",
			Handler:    _EdgeControl_RevokeTarget_Handler,
		},
		{
			MethodName: "PreflightEffect",
			Handler:    _EdgeControl_PreflightEffect_Handler,
		},
		{
			MethodName: "ExecuteEffect",
			Handler:    _EdgeControl_ExecuteEffect_Handler,
		},
		{
			MethodName: "AcknowledgeEffect",
			Handler:    _EdgeControl_AcknowledgeEffect_Handler,
		},
		{
			MethodName: "PrepareRoute",
			Handler:    _EdgeControl_PrepareRoute_Handler,
		},
		{
			MethodName: "CommitRoute",
			Handler:    _EdgeControl_CommitRoute_Handler,
		},
		{
			MethodName: "ResumeRoute",
			Handler:    _EdgeControl_ResumeRoute_Handler,
		},
		{
			MethodName: "ConfigureRuleObservations",
			Handler:    _EdgeControl_ConfigureRuleObservations_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _EdgeControl_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "edge/v1/edge.proto",
}

const (
	ControlSink_CommitResults_FullMethodName           = "/masi.edge.v1.ControlSink/CommitResults"
	ControlSink_PublishRuleObservations_FullMethodName = "/masi.edge.v1.ControlSink/PublishRuleObservations"
	ControlSink_PublishTargetStatus_FullMethodName     = "/masi.edge.v1.ControlSink/PublishTargetStatus"
)

// ControlSinkClient is the client API for ControlSink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlSinkClient interface {
	CommitResults(ctx context.Context, in *InferenceResultBatch, opts ...grpc.CallOption) (*CanonicalAckBatch, error)
	PublishRuleObservations(ctx context.Context, in *RuleObservationBatch, opts ...grpc.CallOption) (*PublishAck, error)
	PublishTargetStatus(ctx context.Context, in *TargetStatusBatch, opts ...grpc.CallOption) (*PublishAck, error)
}

type controlSinkClient struct {
	cc grpc.ClientConnInterface
}

func NewControlSinkClient(cc grpc.ClientConnInterface) ControlSinkClient {
	return &controlSinkClient{cc}
}

func (c *controlSinkClient) CommitResults(ctx context.Context, in *InferenceResultBatch, opts ...grpc.CallOption) (*CanonicalAckBatch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanonicalAckBatch)
	err := c.cc.Invoke(ctx, ControlSink_CommitResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlSinkClient) PublishRuleObservations(ctx context.Context, in *RuleObservationBatch, opts ...grpc.CallOption) (*PublishAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishAck)
	err := c.cc.Invoke(ctx, ControlSink_PublishRuleObservations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlSinkClient) PublishTargetStatus(ctx context.Context, in *TargetStatusBatch, opts ...grpc.CallOption) (*PublishAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishAck)
	err := c.cc.Invoke(ctx, ControlSink_PublishTargetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlSinkServer is the server API for ControlSink service.
// All implementations must embed UnimplementedControlSinkServer
// for forward compatibility.
type ControlSinkServer interface {
	CommitResults(context.Context, *InferenceResultBatch) (*CanonicalAckBatch, error)
	PublishRuleObservations(context.Context, *RuleObservationBatch) (*PublishAck, error)
	PublishTargetStatus(context.Context, *TargetStatusBatch) (*PublishAck, error)
	mustEmbedUnimplementedControlSinkServer()
}

// UnimplementedControlSinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlSinkServer struct{}

func (UnimplementedControlSinkServer) CommitResults(context.Context, *InferenceResultBatch) (*CanonicalAckBatch, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitResults not implemented")
}
func (UnimplementedControlSinkServer) PublishRuleObservations(context.Context, *RuleObservationBatch) (*PublishAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishRuleObservations not implemented")
}
func (UnimplementedControlSinkServer) PublishTargetStatus(context.Context, *TargetStatusBatch) (*PublishAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishTargetStatus not implemented")
}
func (UnimplementedControlSinkServer) mustEmbedUnimplementedControlSinkServer() {}
func (UnimplementedControlSinkServer) testEmbeddedByValue()                     {}

// UnsafeControlSinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlSinkServer will
// result in compilation errors.
type UnsafeControlSinkServer interface {
	mustEmbedUnimplementedControlSinkServer()
}

func RegisterControlSinkServer(s grpc.ServiceRegistrar, srv ControlSinkServer) {
	// If the following call panics, it indicates UnimplementedControlSinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlSink_ServiceDesc, srv)
}

func _ControlSink_CommitResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferenceResultBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlSinkServer).CommitResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlSink_CommitResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlSinkServer).CommitResults(ctx, req.(*InferenceResultBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlSink_PublishRuleObservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleObservationBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlSinkServer).PublishRuleObservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlSink_PublishRuleObservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlSinkServer).PublishRuleObservations(ctx, req.(*RuleObservationBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlSink_PublishTargetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetStatusBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlSinkServer).PublishTargetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlSink_PublishTargetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlSinkServer).PublishTargetStatus(ctx, req.(*TargetStatusBatch))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlSink_ServiceDesc is the grpc.ServiceDesc for ControlSink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlSink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "masi.edge.v1.ControlSink",
	HandlerType: (*ControlSinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitResults",
			Handler:    _ControlSink_CommitResults_Handler,
		},
		{
			MethodName: "PublishRuleObservations",
			Handler:    _ControlSink_PublishRuleObservations_Handler,
		},
		{
			MethodName: "PublishTargetStatus",
			Handler:    _ControlSink_PublishTargetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "edge/v1/edge.proto",
}
